dist: xenial
language: python
python:
  - "3.7"
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml
- codecov
- make clean docs dist
deploy:
  provider: pypi
  user: ohmrefresh
  password:
    secure: "QPPTAvlnHT//cup8zZwb4xup0LKyw8vJw6XinibgCUyDyKTlk29kL6szdpALsPDHP77NuLbnGDlIG2uMz+jYq+gn4BbnYnL0AAf8w/d42Pdx2zBdjbXjVONxdqBmqBXy+EV4+3RdBd2aj15GKDe1a/0PClL9dDb0KOId5skOpaTIy27FtOfuDwAboHj/qmOM/NSs/ftI1FeCXtj1b0td+fEcdYfsRcAZb6dX/kYzyUieFhbHzorpPBAx8j4tUiasg+XkQUvlpNvtFxW08PCcKeqvHMgq5M+TOpdo400x2jkUzmSNONJrR5gqkcSu8UKnkYhj8uT3AS0Q6Y6R6OYfYyEgx3/WJw31DMcPKtcAwOPLne/HHYzghwStIP/N0hkJud5gXZZzjAfirfKyvkmdMwZn+NuwdkMuoz9e90uLp25ypazm83yvXmClmuf3Ft5Xdx4ygqZ2nWO0gUF2Svt256QecYXLgBDuels5IhUkVuL8afS15qQEZ6uhxmNSA3L1mz1+itaF/cEp8pjvk93DTJpir6EuqDD/lPhLychILP29Sez1dA4KiwbdY1W58I6CkipnScn07LVTu27EGNzLMr5g9C1JqhvKrBwft3S9MhYIYk7w6f0uZQbcsxJRCJbUONLIMoJwNaj55U3oK+Nn7A0+oCPGKipHpbDqGqzLB6U="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ohmrefresh/grafana-snapshot