dist: xenial
language: python
python:
  - "3.7"
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml
- codecov
- make clean docs dist
deploy:
  provider: pypi
  user: ohmrefresh
  password:
    secure: "l8Qr822dfvWauCnS4D78kSSEDANd/rwusvO8mh5I0S1zJPZaGrQ+qQ0LNx3mxGcT+9gPPtvn7AnIXar/WdcBEL6+6Md4nXytokKzEoUk95a2Zkx9DJ6dh52S9pt5USY4oOnqLLbwKWQyzNJ0qXjZW1rBQM5CTqsn8BrTFvfhID99Hu6TQdYOBGyb5Hz7BHpK3GFN+Ep1hoJS3Z1vmqiJYjFPux7cx2/J1pcHwLL0CiLONoSKdrkVtEnH1ykZCK3qQsQ7ZlcAn5mce6lWIN7fP/d+LMVnS3xmop8S1py7sV6tPV/5lJL15VIk6KaENmaCwKXk+cAqAEYghcyXYZ4FQF0u9nMFLtDtrHFgP69EqEf7Utua0BkjiPp42mw7ABkGaw5u+B07a2ybYQEXGwvAtktittSb5NlaCoUw8Iat7E/15sAVhdLGwE/nN7st/yR8KD/m5zmkaDal6D/lySHoyNgpyccT6fr81IFcAlOlCT6n9YX110X3b3U5ZNIANPvMQgLldLmfycEQNPl6WwuvmJyjpN6B6xM0TZlKsgopIxejK5buks3wUKBgYgWDhdhKx1wq0PWeLlvWP22VJpZrBj9E+2sPw4gqzsDNszU34t8cU2kyZORA7ugJecOxIthz8HrKtWtvCQvCW6umnE0cajmgg1dAUOPQJyWBHGOQuVQ="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ohmrefresh/grafana-snapshot